---
title: "random forest"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
theme_set(theme_bw())
library(randomForest)
```


```{r}

targets::tar_load("all", store = here::here("_targets"))

```

```{r}
set.seed(1989)
all_combos <- all %>%
  select(richness, abundance) %>%
  distinct()

all_training_rows <- sample.int(nrow(all_combos), size = round(nrow(all_combos)/2), replace = F)

all_training_combos <- all_combos[all_training_rows, ]
all_test_combos <- all_combos[-all_training_rows, ]

all_training <- all_training_combos %>%
  left_join(all)

all_test <- all_test_combos %>%
  left_join(all)

```


```{r}

all.rf <- randomForest(hill1 ~ richness + abundance, data = all_training, xtest = select(all_test, richness, abundance), ytest = all_test$hill1)

all_test$rf.predicted <- all.rf$test$predicted

all_test <- all_test %>%
  group_by(richness, abundance) %>%
  mutate(mean_hill1 = mean(hill1)) %>%
  ungroup()

ggplot(all_test, aes(mean_hill1, rf.predicted, color = abundance/richness))+
  geom_point() +
  geom_line(aes(y = mean_hill1))

```

```{r}

all.lm <- lm(hill1 ~ richness + abundance, data = all_training)

all_test$lm.predicted <- predict(all.lm, newdata = all_test[, c("richness", "abundance")])

ggplot(all_test, aes(mean_hill1, lm.predicted))+
  geom_point() 

summary(all.lm)

```
