---
title: "random forest"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
theme_set(theme_bw())
library(randomForest)
```


```{r}

targets::tar_load("all", store = here::here("_targets"))

```

```{r}
set.seed(1989)
all_combos <- all %>%
  group_by(richness, abundance) %>%
  summarize(mean_h1 = mean(hill1),
            sd_h1 = sd(hill1),
            n_h1 = length(unique(hill1))) %>%
  ungroup() %>%
  filter(n_h1 == 1000)

all_training_rows <- sample.int(nrow(all_combos), size = round(nrow(all_combos)/2), replace = F)

all_training <- all_combos[all_training_rows, ]
all_test <- all_combos[-all_training_rows, ]



```

```{r}

ggplot(all_training, aes(richness, abundance, color = mean_h1)) +
  geom_point()

```


```{r}

all.rf <- randomForest(mean_h1 ~ richness + abundance, data = all_training, xtest = select(all_test, richness, abundance), ytest = all_test$mean_h1, keep.forest =T)

all_test$rf.predicted <- all.rf$test$predicted



ggplot(all_test, aes(mean_h1, rf.predicted))+
  geom_point() +
  geom_line(aes(y = mean_h1))

```


```{r}

allsd.rf <- randomForest(sd_h1 ~ richness + abundance, data = all_training, xtest = select(all_test, richness, abundance), ytest = all_test$sd_h1, keep.forest =T)

all_test$rf.predicted_sd <- allsd.rf$test$predicted



ggplot(all_test, aes(sd_h1, rf.predicted_sd))+
  geom_point() +
  geom_line(aes(y = sd_h1))

```

```{r}

all.lm <- lm(mean_h1 ~ richness + abundance, data = all_training)

all_test$lm.predicted <- predict(all.lm, newdata = all_test[, c("richness", "abundance")])

ggplot(all_test, aes(mean_h1, lm.predicted))+
  geom_point() 

summary(all.lm)

```


```{r}

rf_fs <- read.csv(here::here("mod_compare", "rf_and_fs_samples.csv"))

rf_fs_combos <- rf_fs %>%
  select(richness, abundance) %>%
  distinct() 

rf_fs_pars <- rf_fs_combos %>%
  mutate(r_rf_mean = predict(all.rf,  rf_fs_combos[, c('richness', 'abundance')], type = 'response'),
         r_rf_sd = predict(allsd.rf,  rf_fs_combos[, c('richness', 'abundance')], type = 'response')) %>%
  left_join(all_combos)

rf_sims <- list()

for (i in 1:nrow(rf_fs_pars)) {
  
  these_sims <- data.frame(
    richness = rf_fs_pars$richness[i],
    abundance = rf_fs_pars$abundance[i],
    r_sampled_hill1 = sort(rnorm(1000, mean = rf_fs_pars$r_rf_mean[i], sd = rf_fs_pars$r_rf_sd[i])
  ))
  
  rf_sims[[i]] <- these_sims
  
}


rf_sims <- bind_rows(rf_sims)

```


```{r}

rf_sims <- rf_sims %>%
  mutate(X = row_number() - 1) %>%
  select(-X)

write.csv(rf_sims, here::here("rf_from_r_sims.csv"), row.names = F)

```
