---
title: "Sparse RF"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
library(dplyr)
library(ggplot2)
theme_set(theme_bw())
library(randomForest)

```

```{r}
targets::tar_load("all", store = here::here("_targets"))
```


```{r}
#set.seed(1989)
all_combos <- all %>%
  group_by(richness, abundance) %>%
  summarize(mean = mean(hill1),
            sd = sd(hill1))

all_training_rows <- sample.int(nrow(all_combos), size = round(nrow(all_combos)/2), replace = F)

all_training <- all_combos[all_training_rows, ]
all_test<- all_combos[-all_training_rows, ]

ggplot(all_training, aes(richness, abundance)) +
  geom_point(color = "pink") +
  geom_point(data = all_test, shape = 2) +
  scale_y_log10() +
  scale_x_log10()

```
```{r}
all.rf <- randomForest(mean ~ richness + abundance, data = all_training, xtest = select(all_test, richness, abundance), ytest = all_test$mean)


all_test$rf.predicted <- all.rf$test$predicted


ggplot(all_test, aes(mean, rf.predicted, color = abundance/richness))+
  geom_point() +
  geom_line(aes(y = mean)) +
  scale_color_viridis_c()
all.rf

```

```{r}

all_test$error <- abs(all_test$rf.predicted - all_test$mean) / all_test$mean

ggplot(all_test, aes(richness, abundance, color = log(error))) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10() +
  scale_color_viridis_c()

```

```{r}
allsd.rf <- randomForest(sd ~ richness + abundance, data = all_training, xtest = select(all_test, richness, abundance), ytest = all_test$mean)


all_test$rf.predicted.sd <- allsd.rf$test$predicted


ggplot(all_test, aes(sd, rf.predicted.sd, color = abundance/richness))+
  geom_point() +
  geom_line(aes(y = sd)) +
  scale_color_viridis_c()
allsd.rf
```

```{r}

mean.lm <- lm(mean ~ richness* abundance, data=all_combos)
mean.lm
summary(mean.lm)

all_combos$lm_pred <- predict(mean.lm)

ggplot(all_combos, aes(mean, lm_pred)) + 
  geom_point() +
  geom_line(aes(y = mean))




sd.lm <- lm(sd ~ richness* abundance, data=all_combos)
sd.lm
summary(sd.lm)

all_combos$lm_pred.sd <- predict(sd.lm)

ggplot(all_combos, aes(sd, lm_pred.sd)) + 
  geom_point() +
  geom_line(aes(y = sd))
```


```{r}

gen_hill_draws <- function(a_row) {
  
  vals <- rnorm(1000, mean = a_row[5], sd = a_row[7])
  
  return(data.frame(richness = a_row[1],
                    abundance = a_row[2],
                    hill_from_rf = vals))
  
}

pull_real_vals <- function(a_row, all_draws) {
  
  avail_vals <- filter(all_draws, richness == a_row[1],
                       abundance == a_row[2]) %>%
    select(richness, abundance, hill1)
  
  avail_vals <- avail_vals[1:(min(nrow(avail_vals), 1000)),]
  
  avail_vals
}

```


```{r}

hill_preds <- apply(all_test, 1, FUN = gen_hill_draws)

hill_preds <- bind_rows(hill_preds)

real_hills <- apply(all_test, 1, FUN = pull_real_vals, all_draws = all)

real_hills <- bind_rows(real_hills)

all(real_hills$abundance == hill_preds$abundance)
all(real_hills$richness == hill_preds$richness)


preds_compare <- real_hills %>%
  mutate(predicted_from_rf = hill_preds$hill_from_rf) %>%
  group_by(richness, abundance) %>%
  mutate(predicted_from_rf = sort(predicted_from_rf),
         hill1 = sort(hill1)) %>%
  ungroup()

ggplot(preds_compare, aes(hill1, predicted_from_rf)) + 
  geom_point() +
  geom_line(aes(y = hill1), color = "yellow")

```

```{r, fig.dim = c(10,10)}


ggplot(filter(preds_compare, richness %in% c(min(richness), seq(0, 200, by = 10))), aes(hill1, predicted_from_rf)) +
  geom_point() +
  geom_line(aes(y = hill1)) +
  facet_wrap(vars(richness, abundance), scales = "free")

```