Working through the TensorFlow module for neural net regression: https://www.tensorflow.org/tutorials/keras/regression

(with the ultimate intention of using it on the feasible set data)

To run tensorflow in this notebook remember to change the kernel to `tf2`. I set up this kernel using this tutorial: https://priyanka-dandale.medium.com/how-to-create-a-tensorflow-environment-in-jupyter-notebook-and-use-it-e3815002c031



Had to run these (in seperate cells) because I think this kernel does not _come_ with the packages installed:

`pip install matplotlib`

`pip install pandas`

`pip install -q seaborn`

In [8]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [9]:
np.set_printoptions(precision = 3, suppress = True)

In [10]:
import tensorflow as tf

2023-04-11 10:24:21.746760: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


^^ produced the following:

```
2023-04-11 10:24:21.746760: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
```

Proceeding anyway.

In [11]:
from tensorflow import keras

In [12]:
from tensorflow.keras import layers

In [13]:
print(tf.__version__)

2.11.1


### Auto MPG data

In [14]:
url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'
column_names = ['MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight',
                'Acceleration', 'Model Year', 'Origin']

raw_dataset = pd.read_csv(url, names=column_names,
                          na_values='?', comment='\t',
                          sep=' ', skipinitialspace=True)


In [15]:
dataset = raw_dataset.copy()

In [16]:
dataset.tail()

MPG  Cylinders  Displacement  Horsepower  Weight  Acceleration   
393  27.0          4         140.0        86.0  2790.0          15.6  \
394  44.0          4          97.0        52.0  2130.0          24.6   
395  32.0          4         135.0        84.0  2295.0          11.6   
396  28.0          4         120.0        79.0  2625.0          18.6   
397  31.0          4         119.0        82.0  2720.0          19.4   

     Model Year  Origin  
393          82       1  
394          82       2  
395          82       1  
396          82       1  
397          82       1

In [18]:
dataset = dataset.dropna()
dataset['Origin'] = dataset['Origin'].map({1: 'USA', 2: 'Europe', 3: 'Japan'})
dataset = pd.get_dummies(dataset, columns=['Origin'], prefix='', prefix_sep='')
dataset.tail()


MPG  Cylinders  Displacement  Horsepower  Weight  Acceleration   
393  27.0          4         140.0        86.0  2790.0          15.6  \
394  44.0          4          97.0        52.0  2130.0          24.6   
395  32.0          4         135.0        84.0  2295.0          11.6   
396  28.0          4         120.0        79.0  2625.0          18.6   
397  31.0          4         119.0        82.0  2720.0          19.4   

     Model Year  Europe  Japan    USA  
393          82   False  False   True  
394          82    True  False  False  
395          82   False  False   True  
396          82   False  False   True  
397          82   False  False   True

In [19]:
train_dataset = dataset.sample(frac=0.8, random_state=0)
test_dataset = dataset.drop(train_dataset.index)
